#!/usr/bin/env zsh
yabai -m config layout bsp

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9


yabai -m config window_placement second_child

yabai -m config top_padding    6
yabai -m config bottom_padding 6
yabai -m config left_padding   6
yabai -m config right_padding  6
yabai -m config window_gap     6

yabai -m config split_ratio 0.56
yabai -m config mouse_follows_focus on

yabai -m config window_border off